
ALTER TABLE public.lead_enrichment
  ADD COLUMN IF NOT EXISTS discretionary_income text,
  ADD COLUMN IF NOT EXISTS financial_power integer,
  ADD COLUMN IF NOT EXISTS net_worth text,
  ADD COLUMN IF NOT EXISTS net_worth_midpoint integer,
  ADD COLUMN IF NOT EXISTS home_ownership text,
  ADD COLUMN IF NOT EXISTS home_value integer,
  ADD COLUMN IF NOT EXISTS median_home_value integer,
  ADD COLUMN IF NOT EXISTS mortgage_amount integer,
  ADD COLUMN IF NOT EXISTS owns_investments boolean,
  ADD COLUMN IF NOT EXISTS is_investor boolean,
  ADD COLUMN IF NOT EXISTS owns_stocks_bonds boolean,
  ADD COLUMN IF NOT EXISTS education text,
  ADD COLUMN IF NOT EXISTS occupation text,
  ADD COLUMN IF NOT EXISTS occupation_type text,
  ADD COLUMN IF NOT EXISTS occupation_category text,
  ADD COLUMN IF NOT EXISTS marital_status text,
  ADD COLUMN IF NOT EXISTS age integer,
  ADD COLUMN IF NOT EXISTS generation text,
  ADD COLUMN IF NOT EXISTS ethnicity text,
  ADD COLUMN IF NOT EXISTS language text,
  ADD COLUMN IF NOT EXISTS urbanicity text,
  ADD COLUMN IF NOT EXISTS household_adults integer,
  ADD COLUMN IF NOT EXISTS household_persons integer,
  ADD COLUMN IF NOT EXISTS has_children boolean,
  ADD COLUMN IF NOT EXISTS dwelling_type text,
  ADD COLUMN IF NOT EXISTS length_of_residence integer,
  ADD COLUMN IF NOT EXISTS is_veteran boolean,
  ADD COLUMN IF NOT EXISTS companies jsonb,
  ADD COLUMN IF NOT EXISTS spouse_data jsonb,
  ADD COLUMN IF NOT EXISTS is_primary_identity boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS retargetiq_id integer,
  ADD COLUMN IF NOT EXISTS enrichment_methods_used text[],
  ADD COLUMN IF NOT EXISTS enrichment_match_count integer;
